backend:
  name: 'git-gateway'
  branch: 'master' # Branch to update (optional; defaults to master)
  squash_merges: true
publish_mode: editorial_workflow
media_folder: 'static/img'
public_folder: '/img'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content'
    create: true
    format: 'toml-frontmatter'
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
    summary: "{{dirname}} - {{title}}"
    sortable_fields: ['publishDate', 'lastmod', 'title']
    path: '{{slug}}/index'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publication Date', name: 'publishDate', widget: 'datetime' }
      - { label: 'Last Modified Date', name: 'lastmod', widget: 'datetime', default: '', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', field: { label: 'Tag', name: 'tag', widget: 'string' } }
      - { label: 'Weight', name: 'weight', widget: 'number', default: 0 }
      - { label: 'Google AdSense', name: 'googleAds', widget: 'boolean', default: true }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }