backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content'
    create: true
    slug: '{{fields.slug}}'
    path: '{{slug}}/index'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Last Modified Date', name: 'lastmod', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }