backend:
  name: 'git-gateway'
  branch: 'master' # Branch to update (optional; defaults to master)
media_folder: 'static/img'
public_folder: '/img'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content'
    create: true
    format: 'toml-frontmatter'
    slug: '{{fields.slug}}'
    path: '{{slug}}/index'
    fields:
      - { label: 'Slug (Required)', name: 'slug', widget: 'string' }
      - { label: 'Image (Optional)', name: 'image', widget: 'image', required: false }
      - { label: 'Title (Required)', name: 'title', widget: 'string' }
      - { label: 'Publication Date (Required)', name: 'publishDate', widget: 'datetime' }
      - { label: 'Last Modified Date (Optional)', name: 'lastmod', widget: 'datetime', default: '', required: false }
      - { label: 'Tags (Required)', name: 'tags', widget: 'list', field: { label: 'Tag', name: 'tag', widget: 'string' } }
      - { label: Weight (Required), name: weight, widget: number, default: 0 }
      - { label: 'Google AdSense (Required)', name: 'googleAds', widget: 'boolean', default: true }
      - { label: 'Body (Required)', name: 'body', widget: 'markdown' }