backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
site_url: https://youthful-beaver-3b31c3.netlify.app/
display_url: https://youthful-beaver-3b31c3.netlify.app/
show_preview_links: true
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content'
    create: true
    slug: '{{fields.slug}}'
    path: '{{slug}}/index'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: "YYYY-MM-DD"}
      - { label: 'Last Modified Date', name: 'lastmod', widget: 'datetime', default: "", date_format: "YYYY-MM-DD"}
      - { label: 'Tags', name: 'tags', widget: 'list', field: { label: Tag, name: tag, widget: string } }
      - { label: 'Google AdSense', name: 'googleAds', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }